### ISSUE TITLE
The reposync didn't get triggered when repo changes 

### ISSUE THREAD

**Issue by jzhu077** [kelseyhightower/reposync#1]
I followed the instructions on https://github.com/kelseyhightower/pipeline#deploy-the-reposync-cloud-function to setup the gcloud function `reposync` . 

When I make a push to the forked repo `pipeline-application` on github. Say make a commit to branch `t1`. The github repo didn't get sync to the gcloud repository. 

I think it is because the webhook didn't get set up in the github. Please confirm.

**Comment by kelseyhightower** [comment]
@jzhu077 There is a section in the tutorial that I had to update to ensure the webhook got setup correctly. Give the time of this issue I bet you don't have my latest update: https://github.com/kelseyhightower/pipeline/blob/master/labs/github-repositories.md#create-the-github-webhooks

**Comment by kelseyhightower** [comment]
@jzhu077 In your case you created the webhook on the GitHub repos using a configuration object that wasn't right, the secret was in the wrong place, I've fixed in the guide, so please delete the current webhook entry and rerun those steps to recreate it.

**Comment by jzhu077** [comment]
@kelseyhightower thanks for the update. The repo sync is working now. This issue is now closed.
